### PR TITLE
Fix models refs

### PR DESCRIPTION
**Pull request by PeterNSteinmetz**
This corrects the use imports from mystic.models to models throughout. Was necessary for examples to be run after a setup build.

### CODE REVIEW

**Comment by PeterNSteinmetz** [comment]
Don't understand why this failing in the Travis build with a complaint of no module 'models' when that is clearly a module in the source code.

**Comment by mmckerns** [comment]
The module installs as `mystic.models` but is not listed in `mystic.__init__`, so it does need to be imported separately from `mystic`.  I don't want to have `models` install to a non-mystic namespace.

**Comment by PeterNSteinmetz** [comment]
Well here was the problem I was running into. I clone mystic and then try to run the examples in the PyCharm IDE. The examples would not run properly until I changed their imports to read like 'from models import rosen' rather than from mystic.models import rosen'. 

I would be nice if you just clone the package you can then run the examples, even without installing into the virtual environment being used. One may want to do that when evaluating a number of different possible packages, as I was.

**Comment by mmckerns** [comment]
`mystic` should work if you clone it, then install it.  I think the issue is that `mystic` does not work in `setup.py develop` mode.  On install, there are some directories that need to be moved, and files that are dynamically created... these are things that I plan to change to better conform with recent build norms.

Can you conform that you are attempting to run in `develop` mode?  And, if not, can you better describe how your install works?

**Comment by PeterNSteinmetz** [comment]
Thanks, I did not know about install develop mode, so have not used that. Rather, I simply clone the repository and open the directory with the source in it while working on another project in PyCharm and then ‘attach’ the source directory to that project.

I do a similar thing if working on changes on something like mystic, I just open the source directory as a project and then work on it. Very handy if the examples simply run under those circumstances.

**Comment by mmckerns** [comment]
Basically, you shouldn't work by cloning the source and just working on a package without installing it.  There's no guarantee that it will work if you do that.  However, enough people try to do what you did... so many packages now ensure the code works in this use case.  Essentially, `setup.py develop` is a more formal way to run in "in place" mode.

To make mystic work for `develop` mode, the code needs to be restructured... just not how you have done it.  `mystic` needs to appear at the top-level to establish the namespace for the `mystic` packages.  That means, move `models` to `mystic/models` and so on.

**Comment by mmckerns** [comment]
most of the needed package restructuring for `develop` was done in #171; however models was not moved, so this PR is still relevant.

**Comment by mmckerns** [comment]
should be fixed/obsoleted by #175

**Pull request closed without merging**
